### ISSUE TITLE
Add support for JWT without SD

### ISSUE THREAD

**Issue by awoie** [oauth-wg/oauth-sd-jwt-vc#102]
Ideally, we have one spec for SD-JWT VC and JWT VC. This issue is about adding support for vanilla JWTs.

**Comment by mprorock** [comment]
in progress - stand by...

**Comment by mprorock** [comment]
please take a look - https://github.com/mesur-io/ietf-misc/blob/main/draft-prorock-oauth-jwt-vcs.md 

this should merge everything up - there will definitely need to be an editorial pass.
the md generated `-00` xml/txt versions are good to go from an idnits standpoint

**Comment by OR13** [comment]
Seems like this was merged / should be closed.... We should address the spec title next (in an other issue)

**Comment by awoie** [comment]
Closing this issue as it has been addressed.
