### ISSUE TITLE
Why splitting iss weburl to insert .well-known/jwt-issuer?

### ISSUE THREAD

**Issue by peppelinux** [oauth-wg/oauth-sd-jwt-vc#119]
in https://github.com/vcstuff/draft-terbu-sd-jwt-vc/blob/main/draft-terbu-sd-jwt-vc.md#jwt-issuer-metadata-request

I propose to change the current approach in favor of the solution below:
````
If the `iss` value contains a path component, any terminating `/` MUST be
removed before inserting the `/.well-known/jwt-issuer` at the end of the
path.

The following is a non-normative example of a HTTP request for the JWT Issuer
Metadata configuration when `iss` is set to `https://example.com/user/1234`:


GET /user/1234/.well-known/jwt-issuer HTTP/1.1
Host: example.com
````
I'm aware that https://datatracker.ietf.org/doc/html/rfc8414 defines the current approach but It seems to me that splitting a url, including other path in it, is worst then simply append the .well-known

there are some cases where the webpath matches specific web routing in specific contexts, like `user/1234` might be in a multitenant solution, and givin the .well-known resource in a context coherent path I think it is better.

ps = OIDC Federation 1.0 uses the proposed approach.

**Comment by tlodderstedt** [comment]
As far as I understand, the splitting is required by RFC 5785, which we must comply with to get this specification through the IETF approval process. @selfissued can tell you more about it.

**Comment by peppelinux** [comment]
Well, specifically here
https://openid.net/specs/openid-connect-federation-1_0.html#section-6

In Federation we have them both

**Comment by tlodderstedt** [comment]
That’s an OIDF spec, not an IETF spec. Please talk to Mike about the journey with RFC 8414.

**Comment by peppelinux** [comment]
here I report Mike's comments on OAUTH2-WG

In [https://www.ietf.org/archive/id/draft-terbu-sd-jwt-vc-02.html#section-5.1](https://www.ietf.org/archive/id/draft-terbu-sd-jwt-vc-02.html#section-5.1) (JWT Issuer Metadata Request), I question whether “If the iss value contains a path component, any terminating / MUST be removed before inserting /.well-known/ and the well-known URI suffix between the host component and the path component.” is always the right choice.  Yes, I know that that’s what it takes to conform to RFC 5785 and I wrote similar text at https://www.rfc-editor.org/rfc/rfc8414#section-5 , but practically, the permissions on servers may not be administered in a way that allows tenants to write to this location.

**Comment by danielfett** [comment]
Having .well-known as a 'trusted' source of information in the root of web servers is why RFC5785 uses the 'insertion' rule instead of the 'append' rule. The name of this repository shows why allowing .well-known everywhere is not a great idea: https://github.com/cre8/.well-known

And since we're writing an IETF draft, we'll stick with the IETF rules.
