### ISSUE TITLE
What is the benefit of defining a VC-like data model with JWT claims?

### ISSUE THREAD

**Issue by alenhorvat** [oauth-wg/oauth-sd-jwt-vc#128]
Data model in this document resembles to the ID Token data model as defined in OIDC (with the addition of cnf).

On the other hand, the data model is trying to follow the W3C VC data model.
What is the benefit of this data model over the W3C VC data model (except that the claim names are different and iss can be a URI, and not an object and that JSON-LD is not supported by the data model, which basically excludes some significant use cases such as Europass that are leveraging JSON-LD for internationalization, for example)?

**Comment by tlodderstedt** [comment]
It is simple, leverages all predefined JWT claims (including eKYC), and can be used by people familiar with the JWT model to also implement VCs - with SD-JWT also with selective disclosure capabilities. So it clearly gives an easy migration path from the federated to the issuer-holder-verifier model. 

We tested the idea with some projects and communities and it seems a lot of implementers like that. 

Regarding Europass and other JSON-LD-based credential schemes. There could be another spec defining how SD-JWT could be used with JSON-LD.

**Comment by alenhorvat** [comment]
eKCY defines its own data model same as for ID Token. eKYC can be easily mapped to VCs.
The only real difference is the name of the metadata claims (iss vs issuer, iat vs validFrom, etc.)

But SD-JWT can be used with W3C VCs (bot as SD-JWT is and W3C VCs as they are).

**Comment by tlodderstedt** [comment]
eKYC defines an extension that can be used in any JWTish environment. Doesn't work with W3C VCs due to the split between subject related data (credentialSubject) and metadata (evidence). Ask Mark Haine. 

> But SD-JWT can be used with W3C VCs (bot as SD-JWT is and W3C VCs as they are).
not sure what you mean. can you please explain.

**Comment by alenhorvat** [comment]
We did some mapping in the past (it was some time ago, and I don't remember how far we got):

Evidence in VCs is optional and the model and use of evidence for eKYC doesn't make a lot of sense since eKYC already defines the full data model. eKYC can be nicely modelled within the credential subject. There were discussions around re-using the model of eKYC for expressing different levels of verifications.

Essentially it was something like:



```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Verifiable Global ID",
    "description": "Schema of the Verifiable Global ID for a natural person",
    "type": "object",
    "allOf": [{
            "$ref": "./verifiable-attestation-v1.json"
        },
        {
            "properties": {
                "credentialSubject": {
                    "$ref": "#/definitions/credentialSubjectDef"
                }
            }
        }
    ],
    "definitions": {
        "credentialSubjectDef": {
            "allOf": [{
                    "properties": {
                        "id": {
                            "description": "Defines the DID of the subject that is described by the Verifiable Attestation. This identifier is usually used for cryptographic binding.",
                            "type": "string",
                            "format": "uri",
                            "examples": ["did:ebsi:z...", "did:key:..."]
                        },
                        "claims": {
                            "type": "object",
                            "properties": {

                            }
                        }
                    }
                },
                {
                    "$ref": "./e-kyc-verified_claims-2022-08.json#/definitions/verified_claims_def2"
                }
            ]
        }
    }
}
```

verifiable-attestation-v1.json is the VC data model
e-kyc-verified_claims-2022-08.json#/definitions/verified_claims_def2 - is the JSON schema of the eKYC

**Comment by Sakurann** [comment]
to answer the original question raised in the issue,
- the way VCDM 2.0 is going, it requires data model to be JSON-LD and processed according to JSON-LD rules, so things like `@context is in the payload, we put it to be conformant, but are not processing it` will not be conformant.
- the value of VCDM IMO is defining the concept of a credential in a three party model: issued credential must contain the issuer, the subject, claims about the subject, metadata about the issuance of that credential (iat, exp, etc.) and optionally a cryptographic key. that's it. How to map it to the JWT claims is not the expertise of w3c vc wg nor is well-defined in the documents produced by that group.
- VCDM itself is silent about how to sign/process the `data model`

I would absolutely not equate ID Token data model to a VC data model. VC data model needs one step to get to the ID Token usability which is defining how the concepts defined in VCDM are mapped to the JWT claims and how to sign/process that JWT claimset, which is what this sd-jwt vc draft attempts to do.

**Comment by tlodderstedt** [comment]
@Sakurann 

> OID4VP/OID4VP define those (application/x-www-form-urlencoded and application/json) I do not think sd-jwt vc draft should say anything about that.

I think we need to at least scope the media type definition in the spec as those definitions are related to the `typ` only, not request payload.

**Comment by Sakurann** [comment]
why it can't be left to the protocol? why it can't be `application/json`? just for example: https://openid.bitbucket.io/connect/openid-4-verifiable-credential-issuance-1_0.html#section-7.3-9

**Comment by alenhorvat** [comment]
@Sakurann 

_- the way VCDM 2.0 is going, it requires data model to be JSON-LD and processed according to JSON-LD rules, so things like @context is in the payload, we put it to be conformant, but are not processing it will not be conformant._

Please check the discussion in https://github.com/w3c/vc-data-model/pull/1088 since the conclusion is different.
@Sakurann What do you understand under LD processing?  (LD processing with VCs is used only by: data integrity proofs, selective disclosure that's been just defined, internationalisation, identity matching, some advanced querying)
Since JWS is not using any of that, JWS protection mechanism is not affected by the -LD part.
However, it enable use cases, that want to use the -LD (e.g., ELM v3) for internationalisation etc., to use it.

When VCs are secured with JWS, LD processing is not performed. It MAY be performed, if use case requires it, in the post-processing (after the validation) or rendering phase.

_- the value of VCDM IMO is defining the concept of a credential in a three party model: issued credential must contain the issuer, the subject, claims about the subject, metadata about the issuance of that credential (iat, exp, etc.) and optionally a cryptographic key. that's it. How to map it to the JWT claims is not the expertise of w3c vc wg nor is well-defined in the documents produced by that group._

That's perfectly fine. W3C VCDM is focusing on the VCDM data model.
Note that the current VCDM v2.0, without any JWT claim, is a valid JWT.

_- VCDM itself is silent about how to sign/process the data model_

I think this is a good approach of the specification, since it defines a data model. Securing mechanism should be defined by specifications like JAdES which defines a profile for JSON-based AdES.

**Comment by alenhorvat** [comment]
> why it can't be left to the protocol? why it can't be `application/json`? just for example: https://openid.bitbucket.io/connect/openid-4-verifiable-credential-issuance-1_0.html#section-7.3-9

Reason is simple and it is following the basic architecture/design principles. Signature (e.g., JWS) defines the serialisation and with it the resulting type.  JWS specification cannot and should not know anything about the protocol that will use it.

When a protocol defines a profile or a set of supported elements, the protocol needs to ensure that the media type that's defined consistent with the elements it selected.

**Comment by tlodderstedt** [comment]
@Sakurann Perhaps I did not explain well. 

This is the media type definition from the spec. 
<img width="605" alt="image" src="https://github.com/vcstuff/draft-terbu-sd-jwt-vc/assets/328358/1af7d747-1d74-4327-b0bd-969cff564027">

It does not describe the context where the media type `application/vc+sd-jwt` shall be used. So people might think this is a media type that should be used as content type of an HTTP response. I think we agree this is not the case. All I'm suggesting to document the intended use in the JOSE header (and as format identifier in credential exchange protocols). 

Would you agree?

**Comment by paulbastian** [comment]
> @Sakurann 
> 
> _- the way VCDM 2.0 is going, it requires data model to be JSON-LD and processed according to JSON-LD rules, so things like @context is in the payload, we put it to be conformant, but are not processing it will not be conformant._
> 
> Please check the discussion in https://github.com/w3c/vc-data-model/pull/1088 since the conclusion is different.
> @Sakurann What do you understand under LD processing?  (LD processing with VCs is used only by: data integrity proofs, selective disclosure that's been just defined, internationalisation, identity matching, some advanced querying)
> Since JWS is not using any of that, JWS protection mechanism is not affected by the -LD part.
> However, it enable use cases, that want to use the -LD (e.g., ELM v3) for internationalisation etc., to use it.
> 
> When VCs are secured with JWS, LD processing is not performed. It MAY be performed, if use case requires it, in the post-processing (after the validation) or rendering phase.
> 
> _- the value of VCDM IMO is defining the concept of a credential in a three party model: issued credential must contain the issuer, the subject, claims about the subject, metadata about the issuance of that credential (iat, exp, etc.) and optionally a cryptographic key. that's it. How to map it to the JWT claims is not the expertise of w3c vc wg nor is well-defined in the documents produced by that group._
> 
> That's perfectly fine. W3C VCDM is focusing on the VCDM data model.
> Note that the current VCDM v2.0, without any JWT claim, is a valid JWT.
> 
> _- VCDM itself is silent about how to sign/process the data model_
> 
> I think this is a good approach of the specification, since it defines a data model. Securing mechanism should be defined by specifications like JAdES which defines a profile for JSON-based AdES.
> 
> 
> 
> 
> 

I agree that securing JSON-LD as payload with SD-JWT is important work that should be considered and investigated.
I don't agree that it is a good idea to take VCDM claims and use all of those to secure JWTs, because there are existing claims from JWT claims registry and existing implementations depend on those

**Comment by alenhorvat** [comment]
@paulbastian thank you for your feedback and I fully understand your concern. We need to put things into a context: most of those cases operate within closed systems where everything is well defined - data models, verification rules, etc. Within this context, I fully agree with you.

Securing JSON-LD can be done today by JAdES (pure JWS, no JWT). I believe it is worth to read and reflect on it
https://www.etsi.org/deliver/etsi_ts/119100_119199/11918201/01.01.01_60/ts_11918201v010101p.pdf

From my experience, the @context is really processed (in most cases) outside of the verification scope/process. There are signatures that rely on the context, however, that's not relevant for JWS and this discussion. (In a brute-force scenario context can be embedded/inline and problem solved - size is the price to pay - not in the scope of this discussion)

Since JWT specifies that all claims are optional, libraries should be able to process JWT tokens without any JWT claims (I know how it sounds). From experience, JWS/JWT libraries verify the signature, other verifications are performed manually. People could also argue that VCs are used. This direction won't lead to a solution.

ID Token and eKYC define rules for the JWT claims when they are secured with JWS. I believe there are many other use cases that define profiles, rules, etc.

In an open multi-use case system, there are additional challenges and we had a good discussion with Torsten on the topic where we identified several points that should be considered.

It is worth reflecting on the designs of
- JWS
- JAdES
- linked data proofs
- VCDM v2
on their data model and serialisation.

Back to my question:
What is the real benefit of this data model over the W3C VC data model by looking at the situation objectively?
(I'm also trying to find an answer to the question)

With Torsten we had a very fruitful discussion. We need to reflect on several elements.

Have a nice weekend!

**Comment by alenhorvat** [comment]
@paulbastian , I missed one point.
> I agree that securing JSON-LD as payload with SD-JWT is important work that should be considered and investigated. I don't agree that it is a good idea to take VCDM claims and use all of those to secure JWTs, because there are existing claims from JWT claims registry and existing implementations depend on those

Can you please elaborate on "take VCDM to secure JWT"? 
If my understanding is correct (sometimes is, sometimes isn't), it is JWS the one secures the payload (and it can be any JSON). JWT claims define contextual information: who, validity, about who, for whom. We should reflect on sigTst from JAdES.

I'm personally not proposing to use VCDM to protect a JWT. VCDM and JWT are both protected by JWS.

**Comment by paulbastian** [comment]
As an example, iss and cnf are registered claim names for JWTs that are used to secure the VC. Existing RFCs are using those. Therefore it doesn't make sense to overwrite those by the w3c data model in my opinion

**Comment by alenhorvat** [comment]
Thank you @paulbastian. I understand your view. If VC claims were registered, what would be the benefit of the data model over VCDM? 

Since I’m involved in projects that use VCDM (in JSON and JSON-LD) and also JWT I would really like to understand the objective benefits od the data model.

**Comment by awoie** [comment]
To resolve this issue, we will add a section on relationship to other documents and include a chapter on "VCDM".

**Comment by awoie** [comment]
This issue is ready for a PR.
