### ISSUE TITLE
Make section on public claims to include private claims as well

### ISSUE THREAD

**Issue by awoie** [oauth-wg/oauth-sd-jwt-vc#137]
Currently, we have a section about public claims. This should be either removed or it should be generalized to something like "Additional Claims" where it mentions additional private and public claims MAY be added.

**Comment by tlodderstedt** [comment]
I think this issue was already resolved. The current text is "SD-JWTs VC can contain claims that are registered in "JSON Web Token Claims" registry as defined in [RFC7519], as well as public and private claims."

**Comment by awoie** [comment]
Closing since issue has been addressed.
