### ISSUE TITLE
Clarification on metadata endpoint

### ISSUE THREAD

**Issue by c2bo** [oauth-wg/oauth-sd-jwt-vc#143]
There was an on-going discussion in #101 on the new metadata endpoint, but the discussion should have it's own issue (separated from the naming issue).

Imho, we should add a section that adds more clarity on the intended use of the endpoint introduced in this spec during verification (e.g., by making the resolution of the key using this endpoint mandatory during verification if the JWS header indicates web-based key resolution).
Perhaps adding a small part to the "Verification and Processing" section makes sense?

Prior discussion was here: https://github.com/vcstuff/draft-terbu-sd-jwt-vc/issues/101#issuecomment-1595828680

**Comment by awoie** [comment]
Relates to #168

**Comment by awoie** [comment]
Fixed by #175

**Comment by awoie** [comment]
Closing this issue since we merged PR #175
