### ISSUE TITLE
examples for ARF.

### ISSUE THREAD

**Issue by Sakurann** [oauth-wg/oauth-sd-jwt-vc#144]
moving @tlodderstedt's and my work on adding examples how to represent PID/EAA/mDLs as SD-JWT VC to this repo from the sd-jwt repo.
EAA: https://github.com/oauth-wg/oauth-selective-disclosure-jwt/pull/211
mDL: https://github.com/oauth-wg/oauth-selective-disclosure-jwt/issues/144 and https://github.com/oauth-wg/oauth-selective-disclosure-jwt/pull/233
PID as a reference point: https://github.com/oauth-wg/oauth-selective-disclosure-jwt/pull/304-

**Comment by awoie** [comment]
With the PID example included, can we close this issue, or are there other examples needed as well?

**Comment by danielfett** [comment]
Yes, this can be closed now.
