### ISSUE TITLE
KeyBinding JWT header

### ISSUE THREAD

**Issue by paulbastian** [oauth-wg/oauth-sd-jwt-vc#159]
SD-JWT defines the KB-JWT header, SD-JWT-VC only refers to the claims. Is it necessary to reference to the SD-JWT spec for this?

**Comment by danielfett** [comment]
We do refer to the Key Binding JWT: https://vcstuff.github.io/draft-terbu-sd-jwt-vc/draft-ietf-oauth-sd-jwt-vc.html#name-key-binding-jwt

Is there anything else missing?

**Comment by awoie** [comment]
Closing this issue since #177 got merged.
