### ISSUE TITLE
How to choose `type` values for your credential format?

### ISSUE THREAD

**Issue by danielfett** [oauth-wg/oauth-sd-jwt-vc#171]
We need to give guidance in the spec on choosing `type` values for a credential format.

We need to think about collision resistance - either by a registry or something DNS-based like URIs or java package name notation.

Personal opinion: Use URLs, like XML namespaces. It automatically avoids collisions, there is no registry required for potentially large amounts of values, and we can think about extending this in the future with machine-readable information about credential format.

**Comment by bc-pi** [comment]
@selfissued suggestion is worth consideration: to have a registry and recommend that the type value either be a registered value or be a collision-resistant value.

**Comment by selfissued** [comment]
My suggestion would be to recommend either registering values in a registry that we create as community service and/or to use collision-resistant names, as defined at https://www.rfc-editor.org/rfc/rfc7515.html#section-2.  In particular, if we make a recommendation for using some form of collision-resistant names, we should just cite RFC 7515's definition and not create our own that is similar but different.

**Comment by peacekeeper** [comment]
> How to choose type values

> Use URLs, like XML namespaces. It automatically avoids collisions, there is no registry required

Sounds a bit like you are re-inventing (parts of) JSON-LD :)

**Comment by awoie** [comment]
> > How to choose type values
> 
> > Use URLs, like XML namespaces. It automatically avoids collisions, there is no registry required
> 
> Sounds a bit like you are re-inventing (parts of) JSON-LD :)

Only the requirement that type might have to be a URL bit. JSON-LD is an RDF implementation and therefore has more boilerplate that is not needed that goes beyond this problem.

**Comment by danielfett** [comment]
This PR introduces the requirement for identifiers to be Collision-Resistant Names: https://github.com/oauth-wg/oauth-sd-jwt-vc/pull/173

I still think that moving towards an identifier format that will later allow discoverability of credential rules and policies would be beneficial. For that, I think that URIs would be most useful, as explained above. There is a ton of information that Holders and Verifiers might want to be able to discover:
- What kind of binding is employed for a certain credential type (see https://github.com/oauth-wg/oauth-sd-jwt-vc/issues/145)
- More generally, what data can or cannot be used for checking the holder binding.
- Information about credential types (e.g., display names, colors, logos, etc.) — this clearly overlaps with what is transported by OpenID4VCI today
- A schema for content verification, including what can or cannot be made selectively disclosable
- Information about individual data fields (e.g., the human-readable label for a claim name, including its translations)

**Comment by bc-pi** [comment]
That kind of discoverability could be pointing to or just contained in a human readable spec or document that has that kind of information.

**Comment by danielfett** [comment]
The PR has been merged, but let's use this issue to discuss whether we need discoverability.

@bc-pi That's correct, URLs enable discoverability, but that doesn't mean that they are the only option.

**Comment by peacekeeper** [comment]
> The PR has been merged

I'm not familiar with IETF processes, but merging such breaking changes in less than 24 hours without any chance of community review feels a bit ... hmm ...

**Comment by decentralgabe** [comment]
I am not in favor of a registry. We (Block) are interested in sd-jwt-vc for its simplicity, and would leverage the property to point to JSON Schema documents.

**Comment by danielfett** [comment]
In the editors' call we agreed to close this issue, as the main points have been addressed in the meantime (how to choose type and discoverability).
