### ISSUE TITLE
DID you? 

### ISSUE THREAD

**Issue by bc-pi** [oauth-wg/oauth-sd-jwt-vc#186]
The current text [here in -01](https://www.ietf.org/archive/id/draft-ietf-oauth-sd-jwt-vc-01.html#section-3.5-2.2) is basically a normative requirement to support all DID resolution. Which is too much, even to the extent we want to allow for or support some DID usage. We need to revisit how this is phrased in the document and even how much (if any) is said. 

---------
created from discussion in PR #183 : 

B: "IMHO DIDs can be accounted/allowed for via the "Separate specifications or ecosystem regulations MAY define rules complementing the rules defined above" criteria below and shouldn't receive 1st order treatment like this in the spec."

O: "We added DIDs to make the spec useful also for the credential market that uses DIDs. For those people it is required to demonstrate how that can be done. I'm wondering how other folks are thinking about dropping DIDs from getting 1st order treatment. You are right, one can create another draft that just explains how to use DIDs with this spec."

_Originally posted by @awoie in https://github.com/oauth-wg/oauth-sd-jwt-vc/pull/183#discussion_r1387268502_

**Comment by awoie** [comment]
> The current text [here in -01](https://www.ietf.org/archive/id/draft-ietf-oauth-sd-jwt-vc-01.html#section-3.5-2.2) is basically a normative requirement to support all DID resolution. Which is too much, even to the extent we want to allow for or support some DID usage. We need to revisit how this is phrased in the document and even how much (if any) is said.
> 
> created from discussion in PR #183 :
> 
> B: "IMHO DIDs can be accounted/allowed for via the "Separate specifications or ecosystem regulations MAY define rules complementing the rules defined above" criteria below and shouldn't receive 1st order treatment like this in the spec."
> 
> O: "We added DIDs to make the spec useful also for the credential market that uses DIDs. For those people it is required to demonstrate how that can be done. I'm wondering how other folks are thinking about dropping DIDs from getting 1st order treatment. You are right, one can create another draft that just explains how to use DIDs with this spec."
> 
> _Originally posted by @awoie in [#183 (comment)](https://github.com/oauth-wg/oauth-sd-jwt-vc/pull/183#discussion_r1387268502)_

It was definitely not the intend to support all DID methods and all kind of DID resolutions. We need to make DID support optional for verifiers and if they don't have support they won't be able to verify DID-based SD-JWT VCs which is fine.
