### ISSUE TITLE
Add output example

### ISSUE THREAD

**Issue by tlodderstedt** [oauth-wg/oauth-sd-jwt-vc#194]
I think the understanding of the spec could be further facilitated by adding an example of a SD-JWT VC after the verifier has processed the SD-JWT VC and (basically) has constructed a JWT representation for further processing in the application.

**Comment by bc-pi** [comment]
The new PID example in draft -02/-03 shows the JSON data for "further processing" after validation: https://www.ietf.org/archive/id/draft-ietf-oauth-sd-jwt-vc-03.html#appendix-B.1-56

Does that seem sufficient? Or perhaps a similar addition to the example used in the main body of the [draft](https://www.ietf.org/archive/id/draft-ietf-oauth-sd-jwt-vc-03.html#section-4.2)? Or something different/more?
