### ISSUE TITLE
Consider making cnf optional

### ISSUE THREAD

**Issue by awoie** [oauth-wg/oauth-sd-jwt-vc#196]
Not all VCs require key binding. For those, cnf should be made optional.

**Comment by bc-pi** [comment]
I've read the text in https://www.ietf.org/archive/id/draft-ietf-oauth-sd-jwt-vc-01.html#section-3.2.2.2-3.5.2.1 that says "REQUIRED when Cryptographic Key Binding is to be supported." as `cnf` being optional or not required when key binding isn't needed.

**Comment by awoie** [comment]
Do you think we should also explain the OPTIONAL case or replace the REQUIRED with something else? CONDITIONAL is not a reserved word unfortunately.

**Comment by bc-pi** [comment]
> I would propose to clarify this. From a quick reading this is not obviously optional and it does not match the other claims that only state REQUIRED/OPTIONAL without any conditions. As cryptographic binding is optional, I think this line should begin with "OPTIONAL. [...]"

https://github.com/oauth-wg/oauth-sd-jwt-vc/pull/213 attempts to do just that
