### ISSUE TITLE
out of date terminology

### ISSUE THREAD

**Issue by bc-pi** [oauth-wg/oauth-sd-jwt-vc#197]
https://www.ietf.org/archive/id/draft-ietf-oauth-sd-jwt-vc-01.html#section-3.2.2.2-3.5.2.1 has "Combined Format for Presentation", which isn't used in SD-JWT anymore.

**Comment by awoie** [comment]
I assigned you @bc-pi since you are one of the SD-JWT editor's.

**Comment by bc-pi** [comment]
Gotta start somewhere... hopefully I can handle this one. PR #201 has proposed changes.
