### ISSUE TITLE
Add sd_hash to payload of Key Biniding JWT example

### ISSUE THREAD

**Issue by gmirc12** [oauth-wg/oauth-sd-jwt-vc#206]
According to spec [Key Binding for SD-JWT-VC](https://www.ietf.org/archive/id/draft-ietf-oauth-sd-jwt-vc-01.html#name-key-binding-jwt), 

> the Key Binding JWT MUST adhere to the rules defined in Section 5.3 of [SD-JWT spec](https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-07.html#section-5.3-3.2.1)

This means, that the sd_hash claim has to be included in the payload of the Key Binding JWT. Can you correct the example, given in [SD-JWT-VC with Key Binding example](https://www.ietf.org/archive/id/draft-ietf-oauth-sd-jwt-vc-01.html#section-5.2-1), so that it includes the sd_hash claim?

**Comment by awoie** [comment]
Good catch! We will fix this. Indeed, the sd_hash is missing.

**Comment by awoie** [comment]
@danielfett can you fix the example?

**Comment by bc-pi** [comment]
Looks like we need to switch back to the pointing at the main branch of the sd-jwt-python library for generating the examples. `sd_hash` should show up automagically once that's done.
