### ISSUE TITLE
Add type metadata for basic display/rendering information

### ISSUE THREAD

**Issue by bc-pi** [oauth-wg/oauth-sd-jwt-vc#224]
> This is qualified with "for example" but the type metadata in the PR currently doesn't define this stuff. I'm still unsure about leaving portions of sd-jwt-vc-types like claims and display out of this PR. But should we at least track that in an issue?

_Originally posted by @bc-pi in https://github.com/oauth-wg/oauth-sd-jwt-vc/pull/220#discussion_r1548311395_

the "stuff" mentioned was other content/concepts from https://github.com/vcstuff/sd-jwt-vc-types, which PR #220 was based on

**Comment by bc-pi** [comment]
ideas for metadata from https://github.com/vcstuff/sd-jwt-vc-types

**Comment by danielfett** [comment]
For an MVP (i.e., our next draft release), we should IMO add:

- [ ] Basic display/rendering information for the credential itself
- [ ] Basic display/rendering information for claims
- [ ] JSON schema

**Comment by babisRoutis** [comment]
A single issue tracking the features to be added (from types),  I think, is not so convenient.

Perhaps it would be better to use some more specific labels like for instance `meta-display` and /or `meta-claims` for annotate related issues. In this way, issues reported to types repo can be transferred here and new issues can be added freely.

**Comment by awoie** [comment]
> A single issue tracking the features to be added (from types), I think, is not so convenient.
> 
> Perhaps it would be better to use some more specific labels like for instance `meta-display` and /or `meta-claims` for annotate related issues. In this way, issues reported to types repo can be transferred here and new issues can be added freely.

You can also create new issues if you believe other things are missing for your use case.

**Comment by awoie** [comment]
@bc-pi @danielfett I believe we have addressed all items in this issue in the spec. I believe we can close this issue, right?
