### ISSUE TITLE
SD-JWT-VC Types repository

### ISSUE THREAD

**Issue by babisRoutis** [oauth-wg/oauth-sd-jwt-vc#226]
There is a companion specification for metadata hosted at [SD-JWT-VC Types](https://github.com/vcstuff/sd-jwt-vc-types)

I would like to ask if the aforementioned repository is the correct place to raise some questions or comments about the metadata or the metadata specification will be merged here in SD-JWT-VC?

**Comment by awoie** [comment]
IMO, it would be best if you could already comment on this https://github.com/oauth-wg/oauth-sd-jwt-vc/pull/220 which tries to establish the common framework. If this gets merged, we will create PRs for individual parameters and features of metadata.

**Comment by babisRoutis** [comment]
> IMO, it would be best if you could already comment on this #220 which tries to establish the common framework. If this gets merged, we will create PRs for individual parameters and features of metadata.

Hi @awoie thanks for the reply.

Perhaps yet another naive question, I hope you bear with me :  

Is SD-JWT-VC Types to become a specification on its own thus #220 just tries to connect SD-JWT-VC and SD-JWT-VC types or SD-JWT-VC is going to "absorb" SD-JWT-VC Types ?

I am asking this because the #220 keeps just a sort sub-set of the metadata attributes defined in SD-JWT-VC Types.

**Comment by awoie** [comment]
> > IMO, it would be best if you could already comment on this #220 which tries to establish the common framework. If this gets merged, we will create PRs for individual parameters and features of metadata.
> 
> Hi @awoie thanks for the reply.
> 
> Perhaps yet another naive question, I hope you bear with me :
> 
> Is SD-JWT-VC Types to become a specification on its own thus #220 just tries to connect SD-JWT-VC and SD-JWT-VC types or SD-JWT-VC is going to "absorb" SD-JWT-VC Types ?
> 
> I am asking this because the #220 keeps just a sort sub-set of the metadata attributes defined in SD-JWT-VC Types.

The idea is SD-JWT VC absorbs SD-JWT VC Types feature-by-feature incrementally to give the community a chance to comment on each feature individually. PR #220 is a first step that will allow us to extend the metadata as needed. We have an issue that keeps track of features that were raised by the community already and we are considering for SD-JWT VC here https://github.com/oauth-wg/oauth-sd-jwt-vc/issues/224. 

It is best if you provide your feedback on the PR #220 and/or on the issue here https://github.com/oauth-wg/oauth-sd-jwt-vc/issues/224.

**Comment by babisRoutis** [comment]
Thanks @awoie It is clear now

**Comment by awoie** [comment]
Closing this issue since the question was answered. @babisRoutis please create new issues if you think something else is missing that is not already covered by other issues.
