### ISSUE TITLE
Add 'vct' in well-known registry

### ISSUE THREAD

**Issue by jtalir** [oauth-wg/oauth-sd-jwt-vc#242]
Type Metadata introduced new well-known URI /.well-known/vct/ in "6.3.1. From a URL in the vct" , but this is not reflected in appendix-A.3 Well-Known URI Registry.

Additionally, using <type> in sentence "Metadata can be retrieved from the URL https://<authority>/.well-known/vct/<type>, i.e., by inserting /.well-known/vct after the authority part of the URL." seems to me a little bit confusing as type is considered to refer to whole URI. Maybe use <path> or <uri_suffix>(to include also query and fragment URI components)?

**Comment by bc-pi** [comment]
Thank you and yes, the registration request is missing and needs to be added. And that sentence could also be improved.

**Comment by bc-pi** [comment]
Although the use of .well-known for type metadata is being reconsidered #264
