### ISSUE TITLE
use SD-JWT+KB in place of SD-JWT with a Key Binding JWT

### ISSUE THREAD

**Issue by bc-pi** [oauth-wg/oauth-sd-jwt-vc#243]
As of [SD-JWT -09](https://datatracker.ietf.org/doc/draft-ietf-oauth-selective-disclosure-jwt/09/) which "[Distinguished SD-JWT from SD-JWT+KB](https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-09.html#name-document-history)" the phrase "SD-JWT with a Key Binding JWT" may/should be replaced with "SD-JWT+KB"

**Comment by selfissued** [comment]
I disagree with this, as this textual substitution would make the meaning of the specification less clear.  "SD-JWT with a Key Binding JWT" is an accurate, self-evident description, whereas "SD-JWT+KB" is opaque (at best).  It's not like having an optional key binding be present makes the SD-JWT any less of an SD-JWT, just like having a "cnf" claim present doesn't make a JWT any less a JWT.  In both cases, they are simply utilizing an optional feature, and should continue to be described that way.

**Comment by bc-pi** [comment]
This issue was mostly a note/todo to reconcile terminology usage here with the contributions @bifurcation made to the underlying core SD-JWT document, which were iterated on for over six months before being incorporated https://github.com/oauth-wg/oauth-selective-disclosure-jwt/pull/394 

But I honestly don't care enough about this one to push either way and would happily close, if the other editors are okay with it.

**Comment by danielfett** [comment]
At a minimum we should use the term "SD-JWT+KB" somewhere so that it is clear what we're talking about.
