### ISSUE TITLE
Suggestion: Should this spec be more open to multiple Credential formats? [W3C Verifiable Credentials 2.0]

### ISSUE THREAD

**Issue by goncalo-frade-iohk** [oauth-wg/oauth-sd-jwt-vc#249]
Hi there. Hope everyone is ok. I would like to know your opinion on this subject.

After I read the spec I got the feeling that this spec could be more open to other credential types like W3C Verifiable Credentials 2.0.

An Appendix already exists for W3C Verifiable credentials 2.0 in the [SD-JWT spec](https://datatracker.ietf.org/doc/draft-ietf-oauth-selective-disclosure-jwt/).

The important missing part is about the revocation payload that should always be in plain format.
The problem is in W3C VC 2.0 spec this is called `credentialStatus` not `status` like in this spec and the status-list is of a different type.

I was wondering if this Spec could be more broad so it can support other credentials formats and their revocation mechanisms? Maybe more examples with other credential formats and not describe a single mechanism like `I-D.ietf-oauth-status-list` and leave this to the credential specification itself.

**Comment by bc-pi** [comment]
It sounds like [Securing Verifiable Credentials using JOSE and COSE](https://www.w3.org/TR/vc-jose-cose/) is more along the lines of what you're looking for.

**Comment by goncalo-frade-iohk** [comment]
Hi @bc-pi. First thanks for pointing me to that spec, I had not find it before.

**Comment by awoie** [comment]
Two months since pending close, no further activity, closing this issue.
