### ISSUE TITLE
Non-existent section referred for key binding JWT rules due to a typo

### ISSUE THREAD

**Issue by georgepadayatti** [oauth-wg/oauth-sd-jwt-vc#274]
Section 4.1. Key Binding JWT, says the following:

> If the presentation of the SD-JWT VC includes a Key Binding JWT, the Key Binding JWT MUST adhere to the rules defined in Section 5.3 of [[I-D.ietf-oauth-selective-disclosure-jwt](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-selective-disclosure-jwt-13)].

But Section 5.3 does not exist in the referred spec. Instead, it should be Section 4.3

**Comment by bc-pi** [comment]
Thanks @georgepadayatti! A couple sections in SD-JWT were consolidated around draft 12 or 13 and other sections were renumbered as a result. We'll fix this reference and check for others that might need updating too.

**Comment by bc-pi** [comment]
see #275 including https://github.com/oauth-wg/oauth-sd-jwt-vc/pull/275/commits/5b2589a14d3ece7f1c4b56ad46c2a24455375165
